### ISSUE TITLE
Error when clicking macro or from Profession #2

### ISSUE THREAD

**Issue by Meebsy** [Kruithne/EasyDisenchant#11]
`1x EasyDisenchant\EasyDisenchant-1.1.2.lua:256: Usage: GetContainerItemLink(index, slot)
[C]: in function `GetContainerItemLink'
EasyDisenchant\EasyDisenchant-1.1.2.lua:256: in function `ScanEM'
EasyDisenchant\EasyDisenchant-1.1.2.lua:292: in function `IsItemInOutfit'
EasyDisenchant\EasyDisenchant-1.1.2.lua:334: in function `UpdateItems'
EasyDisenchant\EasyDisenchant-1.1.2.lua:518: in function `OpenWindow'
EasyDisenchant\EasyDisenchant-1.1.2.lua:566: in function `InvokeWindowOpen'
EasyDisenchant\EasyDisenchant-1.1.2.lua:534: in function `?'
FrameXML\ChatFrame.lua:4547: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4215: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:2767: in function <FrameXML\ChatFrame.lua:2760>
[C]: in function `UseAction'
FrameXML\SecureTemplates.lua:346: in function `handler'
FrameXML\SecureTemplates.lua:619: in function <FrameXML\SecureTemplates.lua:567>
[C]: ?
FrameXML\SecureHandlers.lua:266: in function <FrameXML\SecureHandlers.lua:263>
[C]: ?
FrameXML\SecureHandlers.lua:296: in function <FrameXML\SecureHandlers.lua:279>
(tail call): ?

Locals:
(*temporary) = nil
(*temporary) = nil
`
I checked out the closed issues and notice one similar to this in there. Started since updating to v1.1.2

**Comment by Kruithne** [comment]
Sorry this took so long to get resolved. I had issued a fix a while back, but hadn't realized the build was marked as 'Alpha' on Curse, meaning very few users actually got it.

There's a new build going out as I type this which should resolve the issues you're having!
