### ISSUE TITLE
recent update

### ISSUE THREAD

**Issue by starcookies** [Kruithne/EasyDisenchant#15]
with the recent update to easy disenchant, doing /disenchant brings up the window to disenchant but no items appear on the screen to disenchant. also when you pull up the enchanting profession tab the disenchant window doesn't appear either.

**Comment by Kruithne** [comment]
Unable to reproduce that on my end, could you try doing it without any other add-ons and tell me if that works? Failing that, could you grab BugSack/BugGrabber and provide me with the full Lua error that's coming up? Thanks.

**Comment by beardyjay** [comment]
Same issue as above, no extra add-ons running out with BugSack, BugGrabber and EasyDisenchant.

Doing a `/disenchant` gives the following error: 

> 
> 2x Usage: local locations = C_EquipmentSet.GetItemLocations(equipmentSetID)
> [C]: in function `GetItemLocations'
> EasyDisenchant\EasyDisenchant-1.1.4.lua:242: in function `ScanEquipmentManager'
> EasyDisenchant\EasyDisenchant-1.1.4.lua:283: in function `IsItemInOutfit'
> EasyDisenchant\EasyDisenchant-1.1.4.lua:321: in function `UpdateItems'
> EasyDisenchant\EasyDisenchant-1.1.4.lua:505: in function `OpenWindow'
> EasyDisenchant\EasyDisenchant-1.1.4.lua:553: in function `InvokeWindowOpen'
> EasyDisenchant\EasyDisenchant-1.1.4.lua:521: in function `?'
> FrameXML\ChatFrame.lua:4724: in function `ChatEdit_ParseText'
> FrameXML\ChatFrame.lua:4386: in function `ChatEdit_SendText'
> FrameXML\ChatFrame.lua:4422: in function <FrameXML\ChatFrame.lua:4418>
> [C]: in function `ChatEdit_OnEnterPressed'
> [string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
> 
> Locals:
> (*temporary) = "Usage: local locations = C_EquipmentSet.GetItemLocations(equipmentSetID)"

**Comment by Sethok** [comment]
Hi guys, I got the same Problem:

3x Usage: local locations = C_EquipmentSet.GetItemLocations(equipmentSetID)
[C]: in function `GetItemLocations'
EasyDisenchant\EasyDisenchant-1.1.4.lua:242: in function `ScanEquipmentManager'
EasyDisenchant\EasyDisenchant-1.1.4.lua:283: in function `IsItemInOutfit'
EasyDisenchant\EasyDisenchant-1.1.4.lua:321: in function `UpdateItems'
EasyDisenchant\EasyDisenchant-1.1.4.lua:505: in function `OpenWindow'
EasyDisenchant\EasyDisenchant-1.1.4.lua:553: in function `InvokeWindowOpen'
EasyDisenchant\EasyDisenchant-1.1.4.lua:521: in function `?'
FrameXML\ChatFrame.lua:4734: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4396: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4432: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "Usage: local locations = C_EquipmentSet.GetItemLocations(equipmentSetID)"

**Comment by Kruithne** [comment]
Version 1.1.5 has been released to address this issue and will be available on Curse shortly.

Since this was only affecting a small number of users, it was quite annoying to track down. It turns out that it's a bug on Blizzards end, with some of your item sets being broken in the new expansion. EasyDisenchant will now skip over these broken item sets, and print a message in chat informing you which ones are broken. I highly recommended you delete and re-create these item sets.

**Comment by Sethok** [comment]
Great, thank you.
Installing the new update didn't fix it for me, but deleting and recreating the itemsets did.

The update didn't work with the following output

1x EasyDisenchant\EasyDisenchant-1.1.6.lua:256: bad argument #1 to 'format' (string expected, got nil)
[C]: in function `format'
EasyDisenchant\EasyDisenchant-1.1.6.lua:256: in function `ScanEquipmentManager'
EasyDisenchant\EasyDisenchant-1.1.6.lua:287: in function `IsItemInOutfit'
EasyDisenchant\EasyDisenchant-1.1.6.lua:325: in function `UpdateItems'
EasyDisenchant\EasyDisenchant-1.1.6.lua:509: in function `OpenWindow'
EasyDisenchant\EasyDisenchant-1.1.6.lua:557: in function `InvokeWindowOpen'
EasyDisenchant\EasyDisenchant-1.1.6.lua:525: in function `?'
FrameXML\ChatFrame.lua:4734: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4396: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4432: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "Your item set '%s' is broken, delete and re-create it."
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Kruithne** [comment]
Thanks for the report. Just released a fix for that error (c2c2c2ee19b14d658a10b13666e13ee5422508e7) so that it should just tell you an item set is broken without throwing an error.

**Comment by Kruithne** [comment]
Version 1.1.7 is uploaded and will be on Curse shortly.
